import { v4 as uuidv4 } from "uuid";
export const INSTRUMENTS = [
  "BD",
  "SD",
  "LC",
  "MC",
  "HC",
  "RS",
  "CP",
  "CB",
  "CY",
  "OH",
  "CH",
];

export const TRACK_INFO = [
  "Artist",
  "Track",
  "Genre",
  "Year",
  "Label",
  "Country",
];
class Part {
  constructor({ instruments, notes }) {
    this.part = instruments.reduce((acc, inst) => {
      acc[inst] = Array.from({ length: 16 }).map((item, index) =>
        notes[inst] && Array.isArray(notes[inst]) && notes[inst].includes(index)
          ? 1
          : 0
      );
      return acc;
    }, {});
    this.part.uid = uuidv4();
  }
}
export const data = [
  {
    artist: "Afrika Bambaataa",
    track: "Planet Rock",
    color: "#DD311B",
    genre: "Electro",
    year: "1982",
    label: "Tommy Boy Music",
    country: "United States",
    parts: [
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6, 10, 13],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
    ],
    id: 1,
  },
  {
    artist: "Cybotron",
    track: "Clear",
    color: "#E26F0A",
    genre: "",
    year: "",
    label: "",
    country: "",
    parts: [
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6, 10, 13],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
    ],

    id: 2,
  },
  {
    artist: "A Guy Called Gerald",
    track: "Voodoo Ray",
    color: "#FBD700",
    genre: "",
    year: "",
    label: "",
    country: "",
    parts: [
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6, 10, 13],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
    ],

    id: 3,
  },
  {
    artist: "Adonis",
    track: "No Way Back",
    color: "#A7ABA1",
    genre: "",
    year: "",
    label: "",
    country: "",
    parts: [
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
      new Part({
        instruments: INSTRUMENTS,
        notes: {
          BD: [0, 6, 10, 13],
          SD: [4, 12],
          CP: [4, 12],
          CB: [0, 2, 4, 6, 7, 9, 11, 12, 14],
          CH: [0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15],
        },
      }),
    ],

    id: 4,
  },
  {
    artist: "Hashim",
    track: "Al Naafiysh (The Soul)",
    color: "#00BBB4",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 5,
  },
  {
    artist: "Freeez",
    track: "I.O.U",
    color: "#53C8EA",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 6,
  },
  {
    artist: "Warp 9",
    track: "Light Years Away",
    color: "#93D401",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 7,
  },
  {
    artist: "Mantronix",
    track: "Needle To The Groove",
    color: "#7764A0",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 8,
  },
  {
    artist: "C.O.D",
    track: "In The Bottle",
    color: "#718470",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 9,
  },
  {
    artist: "B.B. & Q. Band",
    track: "Genie",
    color: "#B99AC4",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 10,
  },
  {
    artist: "Marvin Gaye",
    track: "Sexual Healing",
    color: "#FC91A3",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 11,
  },
  {
    artist: "Loose Ends",
    track: "Hangin' On A String",
    color: "#f0d78f",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 12,
  },
  {
    artist: "Planet Patrol",
    track: "Play At Your Own Risk",
    color: "#71aad9",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 13,
  },
  {
    artist: "The S.O.S Band",
    track: "Just Be Good To Me",
    color: "#ead594",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 14,
  },
  {
    artist: "LL Cool J",
    track: "Rock The Bells",
    color: "#9a7850",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 15,
  },
  {
    artist: "Yellow Magic Orchestra",
    track: "Thousand Knives",
    color: "#a4e5da",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 16,
  },
  {
    artist: "Strafe",
    track: "Set It Off",
    color: "#F8EE4D",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 17,
  },
  {
    artist: "Drexciya",
    track: "Wavejumper",
    color: "#0194C8",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 18,
  },
  {
    artist: "Paul Hardcastle",
    track: "19",
    color: "#A09959",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 19,
  },
  {
    artist: "Newcleus",
    track: "Jam On It",
    color: "#F28B6C",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 20,
  },
  {
    artist: "Midnight Star",
    track: "Curious",
    color: "#B12970",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 21,
  },
  {
    artist: "Egyptian Lover",
    track: "Egypt, Egypt",
    color: "#C19E0A",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 22,
  },
  {
    artist: "UR",
    track: "The Final Frontier",
    color: "#161111",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 23,
  },
  {
    artist: "Surface",
    track: "Happy",
    color: "#B2B5DD",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 24,
  },
  {
    artist: " Kleeer",
    track: "Intimate Connection",
    color: "#C5274A",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 25,
  },
  {
    artist: "Charanjit Singh",
    track: "Raga Bhairav'",
    color: "#817F24",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 26,
  },
  {
    artist: "Metro",
    track: "Brownstone Express",
    color: "#8A8A8A",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 27,
  },
  {
    artist: "Joyce Sims",
    track: "You Are My) All And Al",
    color: "#F05098",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 28,
  },
  {
    artist: "Keith Sweat",
    track: "Make It Last Forever",
    color: "#BF5728",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 29,
  },
  {
    artist: "Alexander Robotnick",
    track: "Problèmes D'Amour",
    color: "#F1CB2C",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 30,
  },
  {
    artist: "Oppenheimer Analysis",
    track: "The Devil's Dancers",
    color: "#598E34",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 31,
  },
  {
    artist: "Beastie Boys",
    track: "Brass Monkey",
    color: "#B63B3B",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 32,
  },
  {
    artist: "Pretty Tony",
    track: "Fix It In The Mix",
    color: "#94B6B8",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 33,
  },
  {
    artist: "Connie",
    track: "Funky Little Beat",
    color: "#FF99D9",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 34,
  },
  {
    artist: "Dopplereffekt",
    track: "Cellular Phone",
    color: "#A89182",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 35,
  },
  {
    artist: "Ta La Rock",
    track: "It's Yours",
    color: "#FD6227",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 36,
  },
  {
    artist: "Gwen Guthrie",
    track: "Outside In The Rain",
    color: "#5494BF",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 37,
  },
  {
    artist: "I-F",
    track: "Space Invaders Are Smoking Grass",
    color: "#6DEC02",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 38,
  },
  {
    artist: "Klein & MBO",
    track: "Dirty Talk",
    color: "#F1E85F",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 39,
  },
  {
    artist: "52nd Street",
    track: "Tell Me",
    color: "#9559D1",
    genre: "",
    year: "",
    label: "",
    country: "",
    id: 40,
  },
];
